name: anchore-scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchore-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: build local container
      uses: docker/build-push-action@v2
      with:
        tags: "my-web-app:latest
        push: false
        load: true

    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: "my-web-app:latest"
